### PR TITLE
wpa_supplicant: Support for PEAP/MSCHAPv2 via 802.1x

### PR DESCRIPTION
**Pull request by rmk40**
Fairly simple change to compile wpa_supplicant against OpenSSL, so more 802.1x auth methods like PEAP and MSCHAPv2 will work.  By removing eap=MD5 from wpa_supplicant.conf, all compiled auth methods will be supported/attempted.  This was more straightforward than adding additional GUI options with nvram variables.

### CODE REVIEW

**Comment by RMerl** [comment]
Are you sure this works?  Because I don't know if Asuswrt relies on wpa_supplicant, or on Broadcom's closed-source nas service to handle this.

**Comment by rmk40** [comment]
Yes, absolutely certain - I'm actually running with this change now.

# wpa_cli status
Selected interface 'vlan2'
bssid=<<REMOVED>>
ssid=
id=0
wpa_state=COMPLETED
ip_address=<<REMOVED>>
Supplicant PAE state=AUTHENTICATED
suppPortStatus=Authorized
EAP state=SUCCESS
selectedMethod=25 (EAP-PEAP)
EAP TLS cipher=ECDHE-RSA-AES256-SHA
EAP-PEAPv1 Phase2 method=MSCHAPV2

**Comment by rmk40** [comment]
I think I understand the nature of the question better now.  wpa_supplicant is only used for **wired authentication**, which is why the change works.  You're right for wireless, we can't do much there.

**Comment by rmk40** [comment]
Anything I need to change for this to be merged?

**Comment by RMerl** [comment]
Sorry, I just haven't had the time lately to study the change.

**Comment by RMerl** [comment]
This is a fairly niche configuration which I doubt will serve more than a very small number of users, however since the changes are quite minimal and unlikely to cause problems with future GPL merges (one single change to rc/*), I'm willing to merge it in.

**Comment by rmk40** [comment]
Great, thanks!

**Pull request merged**
