### PR TITLE
Fixed bashisms from entware-setup.sh

### PR DESCRIPTION
**Pull request by oittaa**

### CODE REVIEW

**Comment by RMerl** [comment]
What's the difference between the two?  Does this pull request resolve any actual issue?

**Comment by oittaa** [comment]
I just thought it would be better if the script was truly portable. Maybe some other projects want to use the install script where they use Dash or other shell, which doesn't use bashisms like [ a == b ] and echo -e.

**Comment by RMerl** [comment]
Both printf and echo are actually provided by Busybox, not by the shell (which is ash anyway).

**Comment by RMerl** [comment]
Closing this, as I see no reason specific to this project to do these changes.

**Pull request closed without merging**
