### PR TITLE
Fix Login in Windows Explorer

### PR DESCRIPTION
**Pull request by umerov1999**

### CODE REVIEW

**Comment by RMerl** [comment]
What specific issue does this fix?

Is it just a fix, or an update to vsftpd 2.0.5?

**Comment by umerov1999** [comment]
in version 2.05 login in win explorer is fixed, but in 2.04 this function doesn't work

**Comment by RMerl** [comment]
In that case, it might be worth investigating jumping to the latest 2.x version (or at least the latest 2.0x), as it should require minimal changes (if any) to the rest of the firmware.

I experimented with 3.x a while ago, and was unstable on certain router models (can't remember which), in addition to require some changes to the rc code.

**Comment by RMerl** [comment]
vsftpd 3.0.3 has been merged in, which should supersede this pull request.

**Pull request closed without merging**
