### PR TITLE
Sort the DHCP reservation list by IP address

### PR DESCRIPTION
**Pull request by aswild**
It always annoyed me that the DHCP reservation list is sorted by date added rather than something intelligent like IP address, so I decided to do something about that.

I added a javascript function to the DHCP settings page which splits up the string-encoded reservation table, sorts the entries by IP address, then packs everything back into the same string format so the rest of the page can remain untouched.  I also noticed that a couple places in the page's code were using a copy of the `dhcp_staticlist_array` called `dhcp_staticlists` when doing a couple checks for address conflicts.  I cleaned this up so only one copy of the NVRAM setting is loaded. I'm not a Javascript dev, but this seemed like a good way to implement the sorting.

**Testing Info:**
* I cut this branch from the `380.57` tag (previously `378.56_2a`) so that I had a stable base to work on. This file hasn't changed between that tag and the latest `master` so I don't expect any issues.
* Compiled on an Ubuntu 14.04 VM with the lovely [build-asus-merlin](https://github.com/assarbad/build-asuswrt-merlin) script
* Works on my RT-AC87U (and should have global compatibility since it's a web GUI change)
* Tested in Firefox 42, Chrome 46, and IE 11

### CODE REVIEW

**Comment by Pet1Cable** [comment]
Hi there ;-)
Could you be kind enough to provide us with your modified compiled firmware somewhere on the net since I found your ideas & implementations very useful. Thanks!
P.

**Comment by JorisSpekreijse** [comment]
You can download the file and place it in /www in your router.
It is merged in the baseline. That will indicate that the author added it to the code.

B.t.w thanks for the code!

**Comment by aswild** [comment]
Note: It's not quite as simple as copying to /www because the / filesystem is mounted as read-only squashfs, which you can't really edit without recompiling the firmware.

For testing, you **can** use bind mounts to overwrite the file

    # mount --bind /tmp/Advanced_DHCP_Content.asp /www/Advanced_DHCP_Content.asp

However, there's also a step in the build process where the asp files are run through a script which strips out extra whitespace and comment lines, as well as replacing the translation text templates with numbered indices rather than the names in the source code.  The result of this is that mounting the original modified file will result in the DHCP page working, but `[English]` will show up instead of most of the text.

This pull request hasn't been merged yet, so the changes aren't upstream in RMerl's repo. However my fork is identical to the 378.56_2a tag which is stable.

**Comment by JorisSpekreijse** [comment]
You're absolutely right.
I misinterpreted the line "This branch has no conflicts with the base branch.".

**Comment by aswild** [comment]
Update: I've rebased this branch off the latest `380.57` tag, it should still be ready to merge.

**Comment by aswild** [comment]
Closing this PR because #914 implements this better and this PR has been open and inactive for several months anyway.

**Pull request closed without merging**
