### PR TITLE
Added OpenVPN scramble patch, it tested with patched client

### PR DESCRIPTION
**Pull request by tuapuikia**
The patch is to by pass IDS detection and there is 4 option to choose and it must set the same for client and server custom configuration field.

“scramble password” – perform a simple xor operation the packet payload, using a string “password”, you choose password

“scramble reverse” – This simply reverses all the data in the packet. This is enough to get past the regular expression detection in both China and Iran.

“scramble xorptrpos” – This performs a xor operation, utilising the current position in the packet payload.

“scramble obfuscate password” – This method is more secure. It utilises the 3 types of scrambling mentioned above. “password” is a string you choose.

### CODE REVIEW

**Comment by RMerl** [comment]
One of the reasons I'm hesitant in merging this is because it might make it hard for me to do upstream upgrades as new OpenVPN release become available.  For this reason I prefer to keep most third party components as close to their original source code as possible.

Also, this pull request contains a lot of totally unrelated changes.

**Comment by rootless4real** [comment]
For anyone in China, this has become a necessity as all TLS auth exchanges
are interrupted.

On Wed, Feb 11, 2015 at 12:30 PM, Eric Sauvageau <notifications@github.com>
wrote:

> One of the reasons I'm hesitant in merging this is because it might make
> it hard for me to do upstream upgrades as new OpenVPN release become
> available. For this reason I prefer to keep most third party components as
> close to their original source code as possible.
>
> Also, this pull request contains a lot of totally unrelated changes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RMerl/asuswrt-merlin/pull/858#issuecomment-73832825>.
>



-- 
James Fowler/方志宇
santiago@myazcomputerguy.com
rootless@gmail.com
Public Key: http://rootless.googlepages.com/fowler_publickey

**Comment by kevinxucs** [comment]
@rootless4real @tuapuikia 

Consider this: https://github.com/kevinxucs/udpmask

Can be compiled to run on the router

**Comment by rootless4real** [comment]
Awesome. I will try it out right away. Thanks.

On Wed, Feb 11, 2015 at 5:27 PM, Kaiwen Xu <notifications@github.com> wrote:

> @rootless4real <https://github.com/rootless4real> @tuapuikia
> <https://github.com/tuapuikia>
>
> Consider this: https://github.com/kevinxucs/udpmask
>
> Can be compiled to run on the router
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RMerl/asuswrt-merlin/pull/858#issuecomment-73853369>.
>



-- 
James Fowler/方志宇
santiago@myazcomputerguy.com
rootless@gmail.com
Public Key: http://rootless.googlepages.com/fowler_publickey

**Pull request closed without merging**
