### PR TITLE
Add support for iPhone 8, iPhone 8 Plus and iPhone X in NetworkMap

### PR DESCRIPTION
**Pull request by comandrei**
https://www.theiphonewiki.com/wiki/IPhone_8 - d20ap, d201ap
https://www.theiphonewiki.com/wiki/IPhone_8_Plus - d21ap, d211ap
https://www.theiphonewiki.com/wiki/IPhone_X  - d22ap, d221ap

### CODE REVIEW

**Comment by RMerl** [comment]
Note that networkmap is closed source since 382_xxxx, so this change would only apply to the AM380 branch.

**Comment by comandrei** [comment]
Will the 380 branch be supported for a while, or deprecated in favor of 382?
I'm fine with closing this if there is no plan to support it in the near future, otherwise could we merge it in ?

**Comment by RMerl** [comment]
It will depend how quickly Asus is going to migrate the models to the 382 branch.  If it takes too long, I might eventually get a 380.69 release out, in which case I will merge this in.  Otherwise, 380.68_xx would only be for security/bugfixes.

**Comment by gannondroid** [comment]
commit

**Pull request merged**
