### PR TITLE
Add Vodafone R226 USB LTE modem

### PR DESCRIPTION
**Pull request by notz**
It's a clone of the Huawei E5786

### CODE REVIEW

**Comment by notz** [comment]
It's working stable but download speed is limited to 1 mbps. Upload is working normal (40 mbps). Any idea what can be the problem?

**Comment by RMerl** [comment]
No idea, I don't work with USB modems.

**Comment by Thynix** [comment]
Is that enough of a reason to postpone merging this?

@notz I take it the modem doesn't have that behavior on other systems?

**Comment by notz** [comment]
@Thynix it's only working on windows in full speed. But i believe it's a problem of my current firmware of the modem (flashed huawei original firmware to fix the problem as first step, but now i can't go back). I have added this first, i would never have tried to flash a different firmware... But it was working before on tomato firmware at full speed, but there were other problems.

**Comment by pepeEL** [comment]
@notz How you read this info:
```
case SN_Vodafone_R226:
 			fprintf(fp, "DefaultVendor=0x%04x\n",	0x12d1);
 			fprintf(fp, "DefaultProduct=0x%04x\n",	0x1f07);
 			fprintf(fp, "TargetVendor=0x%04x\n",	0x12d1);
 			fprintf(fp, "TargetProductList=%s\n",	"15bf,15c8");
 			fprintf(fp, "MessageContent=%s\n",	"55534243123456780000000000000011062000000100000000000000000000");
 			break;
```

Because i also want add my model modem... but i want read this parameters. Thanks

**Comment by notz** [comment]
I sniffed now my windows driver and updated my patch to the same message content.
Now the device is working at full speed in both directions.

@RMerl Hopefully you can merge this, otherwise i have to build always my own versions.

**Comment by RMerl** [comment]
Shouldn't be a problem to merge it for 380.65, need to take care of other things first.

**Comment by pepeEL** [comment]
@notz tell me how check info about modem and how check in router that my router correct reconized my modem ?

**Comment by notz** [comment]
@pepeEL you need sniffusb (https://github.com/cyphunk/sectk/tree/master/unoften/usbsniff/Windows/SniffUSB-2.0). Check show all devices option. Check for your device id (connected ones do find your modem, perhaps replug the modem to find your id). Now check for an unplugged device with the same vendor id. Install the filter on this device and start logging. Replug the modem. Wait a bit and check the log. The last command send is probably your message content. Also you have now the vendor & product ids.

You can also check here: http://blogger.ziesemer.com/2008/10/alltel-um175al-usb-evdo-ubuntu.html

**Comment by soundyogi** [comment]
@notz 
Sorry in Advance:

I have an R226 that I am desperately trying to flash to a E5786 in 2020.

Any pointers?

Sorry for off-topic.

**Pull request merged**
