### PR TITLE
Allow to copy&paste password on login page

### PR DESCRIPTION
**Pull request by boetschi**
When using a password manager application it's nice to just copy & past your password

### CODE REVIEW

**Comment by urdh** [comment]
This is a good change, because there's really no reason what-so-ever to disable pasting, and it breaks every password manager I know of.

However, I would want to question the whole Javascript thing. Why is the login functionality even implemented so that it depends on Javascript, and more importantly, why hasn't it been tested properly in e.g. Safari (tip: it doesn't work, at all)?

What's wrong with just POSTing the credentials to the CGI script?

**Comment by therealmarv** [comment]
tried also to fix that. See here https://github.com/RMerl/asuswrt-merlin/pull/888 ;)

@urdh the main reason was preventing brute force attacks and make them more complicated as far as I know. That's the way Asus implemented it.

**Comment by jolcese** [comment]
Great change.

**Comment by Ancillas** [comment]
@urdh This drives me nuts too, but it's never broken any password managers for me (I tested with KeePass on Windows and 1Password on Mac).

1Password uses DOM manipulation, and KeePass on Windows uses auto-type, which both allow for automatic username and password entry into the form field.

**Comment by urdh** [comment]
@Ancillas Granted, the way I store the login in 1Password doesn't allow me to auto-fill the password so that's why the paste protection is an issue for me. However, since the whole thing is completely broken in Safari that's pretty much a moot point.

**Comment by therealmarv** [comment]
if you want a temporary solution which works on with the Asus Router and Chrome: a [Extension](https://chrome.google.com/webstore/detail/dont-fuck-with-paste/nkgllhigpcljnhoakjkgaieabnkmgdkb) and its source code: https://github.com/jswanner/DontFuckWithPaste

**Comment by RMerl** [comment]
The reason why I haven't changed this yet is that the login page is new, and Asus are still making a lot of changes to its code.  Rather than having to redo my changes every time, I'm waiting for them to stabilize their design.  The latest GPL release for instance has like half of the page rewritten, therefore any commit would fail to merge.

Closing this for now since it won't merge with the new GPL code once that gets merged in, but adjusting the clipboard handling is already on the roadmap on my end (if Asus doesn't get to it first).

**Comment by ryzhovau** [comment]
> When using a password manager application it's nice to just copy & past your password

> This is a good change, because there's really no reason what-so-ever to disable pasting, and it breaks every password manager I know of.

`Shift` + `Ins`, guys. MS DOS still rules:)

**Comment by RMerl** [comment]
7838 had a lot of changes to the login page, and post-7838 beta have even MORE changes to the file.  Therefore, still not going to make any change to that file until Asus stabilizes its development.

**Comment by mw3demo** [comment]
Looks like Asus is going to build this in, as per official 3.0.0.4.378.9135 :

Modifications
- Added Meo and Movistar ISP profile.
- Adjusted Guest network mac filter maximum client number to 16
- **Allow paste password on login page to fulfil some password management softwares requirement.**
- Show current control channel while value is auto.
- Bandwidth limiter can accept decimal point.
- Unnecessary to reboot router after set allow only spcified IP address to enter GUI.
- Adaptive QoS can now be enabled without assigned upload/ download bandwidth.

**Comment by RMerl** [comment]
Obsoleted by recent Asus changes.

**Pull request closed without merging**
